# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_export.ui'
#
# Created: Mon Nov 24 18:01:46 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_export(object):
    def setupUi(self, export):
        export.setObjectName("export")
        export.resize(400, 240)
        self.buttonBox = QtGui.QDialogButtonBox(export)
        self.buttonBox.setGeometry(QtCore.QRect(80, 200, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtGui.QWidget(export)
        self.widget.setGeometry(QtCore.QRect(20, 150, 361, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.total_scan_lineedit = QtGui.QLineEdit(self.widget)
        self.total_scan_lineedit.setObjectName("total_scan_lineedit")
        self.horizontalLayout_5.addWidget(self.total_scan_lineedit)
        self.widget1 = QtGui.QWidget(export)
        self.widget1.setGeometry(QtCore.QRect(20, 120, 361, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dist_ratio_lineedit = QtGui.QLineEdit(self.widget1)
        self.dist_ratio_lineedit.setObjectName("dist_ratio_lineedit")
        self.horizontalLayout_4.addWidget(self.dist_ratio_lineedit)
        self.widget2 = QtGui.QWidget(export)
        self.widget2.setGeometry(QtCore.QRect(20, 50, 361, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ang_noise_dir_slider = QtGui.QSlider(self.widget2)
        self.ang_noise_dir_slider.setSliderPosition(55)
        self.ang_noise_dir_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ang_noise_dir_slider.setObjectName("ang_noise_dir_slider")
        self.horizontalLayout_2.addWidget(self.ang_noise_dir_slider)
        self.widget3 = QtGui.QWidget(export)
        self.widget3.setGeometry(QtCore.QRect(20, 80, 361, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.widget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dist_noise_dir_slider = QtGui.QSlider(self.widget3)
        self.dist_noise_dir_slider.setSliderPosition(45)
        self.dist_noise_dir_slider.setOrientation(QtCore.Qt.Horizontal)
        self.dist_noise_dir_slider.setObjectName("dist_noise_dir_slider")
        self.horizontalLayout_3.addWidget(self.dist_noise_dir_slider)
        self.widget4 = QtGui.QWidget(export)
        self.widget4.setGeometry(QtCore.QRect(20, 20, 361, 22))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.noise_rate_slider = QtGui.QSlider(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noise_rate_slider.sizePolicy().hasHeightForWidth())
        self.noise_rate_slider.setSizePolicy(sizePolicy)
        self.noise_rate_slider.setSliderPosition(8)
        self.noise_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.noise_rate_slider.setObjectName("noise_rate_slider")
        self.horizontalLayout.addWidget(self.noise_rate_slider)

        self.retranslateUi(export)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), export.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), export.reject)
        QtCore.QMetaObject.connectSlotsByName(export)

    def retranslateUi(self, export):
        export.setWindowTitle(QtGui.QApplication.translate("export", "export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("export", "Total scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.total_scan_lineedit.setText(QtGui.QApplication.translate("export", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("export", "Distance ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.dist_ratio_lineedit.setText(QtGui.QApplication.translate("export", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("export", "Angle noise direction:     ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("export", "Distance noise direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("export", "Noise rate:", None, QtGui.QApplication.UnicodeUTF8))

