# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapcreater.ui'
#
# Created: Mon Nov 24 18:01:45 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mapcreater(object):
    def setupUi(self, mapcreater):
        mapcreater.setObjectName("mapcreater")
        mapcreater.resize(800, 600)
        mapcreater.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(mapcreater)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        mapcreater.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mapcreater)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mapcreater.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mapcreater)
        self.statusbar.setObjectName("statusbar")
        mapcreater.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(mapcreater)
        self.toolBar.setObjectName("toolBar")
        mapcreater.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionExport = QtGui.QAction(mapcreater)
        self.actionExport.setChecked(False)
        self.actionExport.setObjectName("actionExport")
        self.actionDrawMap = QtGui.QAction(mapcreater)
        self.actionDrawMap.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawMap.setIcon(icon)
        self.actionDrawMap.setObjectName("actionDrawMap")
        self.actionDrawRoute = QtGui.QAction(mapcreater)
        self.actionDrawRoute.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/route.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawRoute.setIcon(icon1)
        self.actionDrawRoute.setObjectName("actionDrawRoute")
        self.actionClose = QtGui.QAction(mapcreater)
        self.actionClose.setObjectName("actionClose")
        self.actionEraser = QtGui.QAction(mapcreater)
        self.actionEraser.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEraser.setIcon(icon2)
        self.actionEraser.setObjectName("actionEraser")
        self.actionNew = QtGui.QAction(mapcreater)
        self.actionNew.setObjectName("actionNew")
        self.actionPen = QtGui.QAction(mapcreater)
        self.actionPen.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPen.setIcon(icon3)
        self.actionPen.setObjectName("actionPen")
        self.actionAbout = QtGui.QAction(mapcreater)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionDrawMap)
        self.toolBar.addAction(self.actionDrawRoute)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEraser)
        self.toolBar.addAction(self.actionPen)
        self.toolBar.addSeparator()

        self.retranslateUi(mapcreater)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), mapcreater.close)
        QtCore.QMetaObject.connectSlotsByName(mapcreater)

    def retranslateUi(self, mapcreater):
        mapcreater.setWindowTitle(QtGui.QApplication.translate("mapcreater", "Map Creater", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mapcreater", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("mapcreater", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("mapcreater", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("mapcreater", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawMap.setText(QtGui.QApplication.translate("mapcreater", "DrawMap", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawMap.setToolTip(QtGui.QApplication.translate("mapcreater", "DrawMap", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawRoute.setText(QtGui.QApplication.translate("mapcreater", "DrawRoute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawRoute.setToolTip(QtGui.QApplication.translate("mapcreater", "DrawRoute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("mapcreater", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEraser.setText(QtGui.QApplication.translate("mapcreater", "Eraser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEraser.setToolTip(QtGui.QApplication.translate("mapcreater", "Eraser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("mapcreater", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("mapcreater", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPen.setText(QtGui.QApplication.translate("mapcreater", "Pen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPen.setToolTip(QtGui.QApplication.translate("mapcreater", "Pen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mapcreater", "About", None, QtGui.QApplication.UnicodeUTF8))

